# -*- coding: utf-8 -*-
"""ocr&preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJM9jFC1OO1IoKipILoKTgfPtsY4AJVz
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/HARISHLAL007/insider_task2.git
# %cd insider_task2

!git config --global user.name "Heerak"
!git config --global user.email "heeraktiwari1@gmail.com"

!pip install easyocr pdf2image pillow opencv-python

import easyocr
import re

reader = easyocr.Reader(['en'])

try:
    result = reader.readtext('sample_paper.jpg', detail=0)
except:
    print("Error: Image not found or unreadable")
    result = []

def preprocess(lines):
    clean_lines = []

    for line in lines:
        line = line.strip()

        if len(line) < 3:
            continue

        if "page" in line.lower():
            continue

        line = line.replace("0ption", "option")

        line = re.sub(r'[A-Da-d][\.\)]',
              lambda x: x.group().lower().replace('.', ')'),
              line)


        line = re.sub(r'[^a-zA-Z0-9().?,+\-*/= ]', '', line)

        clean_lines.append(line)

    return clean_lines

clean_lines = preprocess(result)

for line in clean_lines:
    print(line)